import {test, expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('demo-tour-completed','true'));});
for(const kind of ['expenses','income']) test(`${kind} can edit notes recurrence and exclusion after creation`,async({page})=>{
 await page.goto(`/demo/${kind}`);
 const edit=page.getByRole('button',{name:kind==='expenses'?'Edit expense':'Edit income',exact:true}).first();
 await edit.click();
 await expect(page.getByRole("dialog", {name:kind === "expenses" ? "Edit Expense" : "Edit Income"})).toBeVisible();
 await expect(page.locator("tbody input, tbody textarea, tbody select")).toHaveCount(0);
 await page.getByRole('textbox',{name:'Notes',exact:true}).fill('Updated note after creation');
 await page.getByRole('checkbox',{name:'Recurring',exact:true}).check();
 await page.getByRole('combobox',{name:'Frequency',exact:true}).selectOption('yearly');
 await page.getByRole('checkbox',{name:'Exclude from monthly totals',exact:true}).check();
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await edit.click();
 await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Updated note after creation');
 await expect(page.getByRole('combobox',{name:'Frequency',exact:true})).toHaveValue('yearly');
 await expect(page.getByRole('checkbox',{name:'Exclude from monthly totals',exact:true})).toBeChecked();
 await page.getByRole('textbox',{name:'Notes',exact:true}).fill('Discard this edit');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await edit.click();
 await expect(page.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('Updated note after creation');
});
test('subscription pencil opens complete editable form',async({page})=>{
 await page.goto('/demo/subscriptions');
 await page.getByRole('button',{name:'Edit subscription',exact:true}).first().click();
 const d=page.getByRole('dialog',{name:'Edit Subscription'});
 await d.getByRole('textbox',{name:'Name',exact:true}).fill('Updated subscription');
 await d.getByRole('textbox',{name:'Notes',exact:true}).fill('New billing instructions');
 await d.getByRole('combobox',{name:'Category',exact:true}).selectOption({index:1});
 const category=await d.getByRole('combobox',{name:'Category',exact:true}).inputValue();
 await d.getByRole('combobox',{name:'Default pay from',exact:true}).selectOption({index:1});
 const payment=await d.getByRole('combobox',{name:'Default pay from',exact:true}).inputValue();
 await d.getByRole('combobox',{name:'Frequency',exact:true}).selectOption('yearly');
 await d.getByRole('button',{name:'Save Changes',exact:true}).click();
 await expect(d).not.toBeVisible();
 await page.getByRole('row').filter({hasText:'Updated subscription'}).getByRole('button',{name:'Edit subscription'}).click();
 await expect(d.getByRole('textbox',{name:'Notes',exact:true})).toHaveValue('New billing instructions');
 await expect(d.getByRole('combobox',{name:'Category',exact:true})).toHaveValue(category);
 await expect(d.getByRole('combobox',{name:'Default pay from',exact:true})).toHaveValue(payment);
 await expect(d.getByRole('combobox',{name:'Frequency',exact:true})).toHaveValue('yearly');
});
